### ISSUE TITLE
Change ElementaryOS to elementary OS?

### ISSUE THREAD

**Issue by aleksandar-todorovic** [s-kaczmarek/elementaryOS_indicators_ultimate_collection#1]
Hi,

Thanks for making this. I only have a slight suggestion. elementary OS should be spelled like this, with small letter 'e' in the beginning and an empty space between the word elementary and the word OS.

I think it might be more appropriate if you change the spelling.

**Comment by s-kaczmarek** [comment]
Hello,

Thank you for interest in my repository. It is impossible to make repository name with empty space. I have changed uppercase "E" to small letter. Is that ok now?

**Comment by aleksandar-todorovic** [comment]
Well, it's better than before. I know that you can't change the name of the repository now.

I created a Pull Request (#2) with the changes in README.md that fixes this completely.

**Comment by aleksandar-todorovic** [comment]
Just found out that you have the same issue in the description of the repository. You can also change that.

**Comment by s-kaczmarek** [comment]
ok, thanks!
